name: user_management_app
description: Aplicación de gestión de usuarios con Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Persistencia de datos
  shared_preferences: ^2.2.2

  # Formateo de fechas y localización
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter y análisis de código
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/data/locations.json
